### ISSUE TITLE
Invisibles are red in Sublime 3149

### ISSUE THREAD

**Issue by outaTiME** [dempfi/ayu#162]
<img width="1392" alt="screen shot 2017-10-13 at 11 57 36" src="https://user-images.githubusercontent.com/140472/31552388-b8b8722a-b00d-11e7-8241-752510e27098.png">

**Comment by dempfi** [comment]
hey @outaTiME will fix it soon

**Comment by dempfi** [comment]
@outaTiME fixed in https://github.com/dempfi/ayu/releases/tag/3.2.2

**Comment by outaTiME** [comment]
woow awesome @dempfi, already published for package control ? i dont see available this version =(

**Comment by dempfi** [comment]
Package control will fetches releases by its own. It should be available soon :)

**Comment by outaTiME** [comment]
Great it wooorks !!! thanks

**Comment by fdeneux** [comment]
Issue persists for sass/scss files:

![screen-shot-2017-11-06-18-07-07](https://user-images.githubusercontent.com/2846577/32453756-6e7bb136-c31d-11e7-881d-1170559e59d9.png)

**Comment by fdeneux** [comment]
@dempfi, are you able to reproduce the issue?

**Comment by dempfi** [comment]
@fdeneux not on the latest version. Can you please try with 4.0.0 and reopen this issue still exists. Also, what syntax highlighting plugin do you use for `scss`, I tested with https://packagecontrol.io/packages/Sass?

**Comment by fdeneux** [comment]
@dempfi, issue was [Color Highlighter](https://packagecontrol.io/packages/Color%20Highlighter) still using an old version of the Ayu Mirage color scheme. Removing the color scheme in `/User/Color Highlighter/themes` makes CH copy the latest version.
